// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlqPyZ-Rgtorq0S_oBUeGVr9-Dsr0-_JA',
    appId: '1:361953437980:web:6c2a1872d3f92e4861f2d9',
    messagingSenderId: '361953437980',
    projectId: 'sqflite-c1710',
    authDomain: 'sqflite-c1710.firebaseapp.com',
    storageBucket: 'sqflite-c1710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmvEQHUh31iFSWBW8e8sgXRha-FeMLnU',
    appId: '1:361953437980:android:1fff52edf05ef33c61f2d9',
    messagingSenderId: '361953437980',
    projectId: 'sqflite-c1710',
    storageBucket: 'sqflite-c1710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ECGAPbaCdlQPb5L0Vppy5pQ69C7VlHg',
    appId: '1:361953437980:ios:a7d12bc2147bcbb161f2d9',
    messagingSenderId: '361953437980',
    projectId: 'sqflite-c1710',
    storageBucket: 'sqflite-c1710.appspot.com',
    iosBundleId: 'com.example.sqfliteApplication',
  );
}
